{% set name = "RSeq" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
#  path: ../../testproject
  git_url: https://github.com/millerh1/conda-testing.git
  git_rev: v1.4
  git_depth: 5

test:
  commands:
    - RSeq
